# Minio Dockerfile
FROM quay.io/minio/minio AS minio-base
 
ENV MINIO_ROOT_USER="root" 
ENV MINIO_ROOT_PASSWORD="jerinminioserver"
ENV MINIO_REGION_NAME="us-east-1"
ENV MINIO_REGION="us-east-1"
ENV MINIO_DOMAIN="minio"

RUN mkdir /usr/nessie/
RUN mkdir /usr/nessie/nessie-dev

RUN chmod -R 777 /usr/nessie/

WORKDIR /usr/nessie/nessie-dev

# Start Minio Server
COPY entrypoint-minio.sh .

ENTRYPOINT ["./entrypoint-minio.sh"]

# CMD [ "tail","-f","/dev/null" ]