# Unity Catalog Openjdk 17 image
FROM quay.io/minio/minio AS minio-base
 
ENV MINIO_ROOT_USER="root" 
ENV MINIO_ROOT_PASSWORD="jerinminioserver"
 
RUN mkdir /usr/unitycatalog/
RUN mkdir /usr/unitycatalog/unity-catalog-dev

RUN chmod -R 777 /usr/unitycatalog

WORKDIR /usr/unitycatalog/unity-catalog-dev

# Start Minio Server
COPY entrypoint-minio.sh .

ENTRYPOINT ["./entrypoint-minio.sh"]

# CMD [ "tail","-f","/dev/null" ]