FROM quay.io/jupyter/datascience-notebook:python-3.11

USER root

RUN apt-get update && \
    apt-get install -y openjdk-11-jdk && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Set JAVA_HOME environment variable
ENV JAVA_HOME=/usr/lib/jvm/java-1.11.0-openjdk-amd64/
ENV PATH=$JAVA_HOME/bin:$PATH

COPY ./requirements.txt .
RUN pip3 install -r requirements.txt

WORKDIR /home/spark/

# Define a volume
VOLUME ["/home/spark/"]