# Openjdk 17 image
FROM debian:bullseye

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
      sudo \
      curl \
      vim \
      unzip \
      rsync \       
      openjdk-17-jdk \
      build-essential \
      software-properties-common \
      ssh \
      git && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Create working folder 
RUN mkdir /usr/unitycatalog

# Assign work directory
WORKDIR /usr/unitycatalog

#Clone UnityCatalog repository
RUN ssh-keygen -t rsa -b 4096 -C "jerinsam16@gmail.com" && \
ssh-add ~/.ssh/id_rsa && \
# Add SSH Key to github
cat ~/.ssh/id_rsa.pub && \
GIT_SSH_COMMAND="ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" git clone -q git@github.com:unitycatalog/unitycatalog.git && \



# Keep the container running
CMD ["tail", "-f", "/dev/null"]
 