# Unity Catalog Openjdk 17 image
FROM quay.io/minio/minio AS minio-base
 
ENV MINIO_ROOT_USER="root" 
ENV MINIO_ROOT_PASSWORD="jerinminioserver"
ENV MINIO_REGION_NAME="us-east-1"
ENV MINIO_REGION="us-east-1"
ENV MINIO_DOMAIN="minio"
 
RUN mkdir /usr/spark
RUN mkdir /usr/spark/iceberg

RUN chmod -R 777 /usr/spark/

WORKDIR /usr/spark/iceberg

# Start Minio Server
COPY entrypoint-minio.sh .

ENTRYPOINT ["./entrypoint-minio.sh"]

# CMD [ "tail","-f","/dev/null" ]