# Unity Catalog Openjdk 17 image
FROM node:22-alpine

RUN apk add --no-cache \
    sudo \
    curl \
    vim \
    unzip \
    rsync \
    openjdk17 \
    build-base \
    openssh \
    git \
    python3 \
    py3-pip \
    make \
    g++ \
    bash \
    gcc \
    g++ \
    python3-dev \
    musl-dev \
    make

# Create working folder 
RUN mkdir /usr/unitycatalog

# Assign work directory
WORKDIR /usr/unitycatalog

# Configure Git to use HTTP/1.1
RUN git config --global http.version HTTP/1.1

#Clone UnityCatalog repository
RUN git clone -q https://github.com/unitycatalog/unitycatalog.git

# Add to Environment Variables 
ENV PATH="/usr/unitycatalog/unitycatalog/bin:/usr/unitycatalog/unitycatalog/ui:${PATH}"
ENV UNITYCATALOG_HOME="/usr/unitycatalog/unitycatalog"

# Run YARN for Unity Catalog UI
WORKDIR /usr/unitycatalog/unitycatalog
 

# Start Unity Catalog Server and UI
COPY entrypoint-unitycatalog.sh .
ENTRYPOINT ["./entrypoint-unitycatalog.sh"]

# # Install Yarn - Commenting as Yarn is already installed
# RUN npm install --global yarn
 